//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCheckersDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendPlayer
    {
        public int Id { get; set; }
        public int IdPlayer { get; set; }
        public int IdFriend { get; set; }
        public string RequestStatus { get; set; }
        public string TypeNotification { get; set; }
    }
}
