//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCheckersDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Gamertag { get; set; }
        public string PlayerStatus { get; set; }
        public Nullable<int> GamesWon { get; set; }
        public Nullable<int> NumberGames { get; set; }
    }
}
